version: "3.9"
services:
  web:
    build: .
    command: ./scripts/start-rails.sh
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      RACK_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: webpacker
    links:
      - webpacker
  webpacker:
    build: .
    command: ./scripts/start-webpack.sh
    ports:
      - 3035:3035
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
